### ISSUE TITLE
The search bar isn't working

### ISSUE THREAD

**Issue by ayyyyyyyyyyy** [tchoulihan/torrenttunes-client#16]
I can type the search terms but when I hit Enter or click the search icon, the client (web client) doesn't respond.

**Comment by tchoulihan** [comment]
The search bar is a dropdown, just click on what you want. Because it searches different search sets(Albums, Artists, and Songs), there isn't really a good way for the enter or search button to know which search set you're using.

You can just click the dropdown, it works fine in firefox, chrome and safari. What browser are you using?

**Comment by tchoulihan** [comment]
Haven't heard anything back on this, closing.
