### ISSUE TITLE
Improve browse bands

### ISSUE THREAD

**Issue by Saphyel** [tchoulihan/torrenttunes-client#18]
I think will be better if you add icons/boxes with the picture of every band, and sort/filter option !

And use better names rather than DerpTest...

**Comment by tchoulihan** [comment]
I actually used to have it set up where the browse would be panels instead of simple text, and their artist image shown instead.

It just got to be too much data though, the page took forever to load. 

Adding a category browser would be good though, I'll have to think of a good way to do this.

What other sorting options could be added?

**Comment by Saphyel** [comment]
You can do it like spotify, pagination in the same page.
I think the most important for sort are: Artist, Year, Album, Song name... The others fields are not priority

As a personal opinion categories for music is useless, a lot of bands start with one genre, evolve to 3 or 4 genres at same time and end with a complete different genres.

**Comment by tchoulihan** [comment]
Right now I only have artists browse-able. Putting every album / song on the browse page wouldn't be good, the page would would be wayy too long.

The search bar at the top does what you're saying; its not sortable, but it searches on all those fields except for year.

I agree that categories are somewhat useless. I did have one request for categories though, because someone wanted to see all the techno groups for instance.

I'll hold off on this for now until I see something that really blows my hair back. I've reverse engineered a lot of spotify/rdio but I found their browse tabs to be bloated as shit.

**Comment by Saphyel** [comment]
@tchoulihan Do you have access to Last.fm API or something similar for get "categories" or "bio" or others fields? I feel bad for don't look before ask.

**Comment by tchoulihan** [comment]
That's okay. I'm only using the open musicbrainz API, and I'll probably stick with that since it doesn't require registering and signing up for an API key or anything.

I already have music categories, they're called tags:
 http://torrenttunes.ml/?artist=83b9cbe7-9857-49e2-ab8e-b57b01038103

and the bio's I decided to leave off, and instead just provide a link to wikipedia. If I go to a music site, I want to see their music at the top of the page, not their bios.

**Comment by tchoulihan** [comment]
Haven't heard anything back from this in a while, I'll close it out for now.
