### ISSUE TITLE
When I share an album, Musicbrainz doesn't recognize all songs

### ISSUE THREAD

**Issue by Clarin98** [tchoulihan/torrenttunes-client#36]
I share an album that Musicbrainz recognize, but not all songs are "accepted"
A screenshot: 
![captura de pantalla de 2015-09-28 20 54 44](https://cloud.githubusercontent.com/assets/14655066/10153726/e89e299c-6624-11e5-9913-b07111a39cdd.png)

**Comment by tchoulihan** [comment]
The reason is because one of the id3 tags, or the song duration is outside a 15 second window.

Here are the 5 pieces of information that need to be correct:

    track title
    track #
    artist name
    album name
    song duration

What I do is go to http://musicbrainz.org/ and make sure my song tags **exactly** match those. Like copy and paste them if you know its the right song.

I've only had a few cases after that fail, like if the song duration is way off. I've had to increase the song duration accepted window many times, right now its at 15 seconds, but don't really want to increase it any more because I don't want mistagged songs.
