### ISSUE TITLE
Add to timeout count on server when a song times out.

### ISSUE THREAD

**Issue by tchoulihan** [tchoulihan/torrenttunes-client#37]

**Comment by Clarin98** [comment]
Hey, I have a question (In fact, I lost my work because I disconnect the client for one hour more or less). When you need move your pc to another place, you need close the app. But this timeout will erase every song uploaded and you can lost your work, only for a simple fact. I suggest you that establish a lax control (more hours) to bring opportunities to real supporters.

**Comment by tchoulihan** [comment]
>  But this timeout will erase every song uploaded and you can lost your work, only for a simple fact.

No, adding to the timeout count is just for my server purposes. However, I have been removing songs in these past few days from a few seeders who I can't download from. As I said, torrenttunes will only hold available music, and if you aren't seeding, and a client can't download a song within 15 minutes, then I will remove those songs.
