### ISSUE TITLE
Play all Button

### ISSUE THREAD

**Issue by Nutomic** [tchoulihan/torrenttunes-client#4]
It seems you can only play one song at a time, or add one song at a time to the queue. It should be possible to play all songs in an album, or all trending songs with a single button.

**Comment by tchoulihan** [comment]
Hey, I actually do have this feature available on the clients(playing whole albums), but I took it off from the web version for now. 

It was just putting too much of strain on my home internet connection(since I'm the only seeder for 99% of everything at the moment). 

I do have it available on the client, because then you'd be helping to seed the songs at that point.

I'll definetely add it back in once more seeders join the network.

**Comment by tchoulihan** [comment]
Just want to note that this is fixed in the latest release.
