### ISSUE TITLE
Use NFO-data instead of Musicbrainz for initial scraping

### ISSUE THREAD

**Issue by tritnaha** [tchoulihan/torrenttunes-client#48]
Instead of having to query musicbrainz for info with every single file, you could scan the directory for the existance of nfo-files and scrape the data off that if it exists, at least initially.

[nfo-files](https://en.wikipedia.org/wiki/.nfo) are used within [the scene](https://en.wikipedia.org/wiki/Warez_scene) and [contain all the valuable information about the release](http://nfodb.net.ru/nfo-555473-VA_-_Dance_Vibez_Vol_3-WEB-2007-ZzZz.html), meaning you wouldn't really have to ping someplace like musicbrainz like crazy. Quality is also guaranteed as releases that are sub-par or break [rules (FLAC)](https://scenerules.org/t.html?id=2012_FLAC.nfo)/[rules (MP3)](https://scenerules.org/t.html?id=2014_MP3.nfo) will automatically be [nuked](https://en.wikipedia.org/wiki/Nuke_%28warez%29).

**Comment by tchoulihan** [comment]
Do these nfo files contain the musicbrainz id for each song within them?

**Comment by tritnaha** [comment]
No they do not, not using any external service at all in that regard. No real need. My suggestion would be to use the info off the nfo's initially as this should be reliable enough, doing this would speed up the library-creation by a significant part. I do not know if this is possible, but wouldn't it be a decent idea to either offload musicbrainz and host a local copy/dump someplace ourselves or ship torrenttunes with a standard, recent musicbrainz db that it can use for faster indexation/tagging? You could probably work some rsync/zsync-magic into it to fetch daily/weekly/monthly updates of said database - Or query the musicbrainz-server we would run ourselves.

**Comment by tchoulihan** [comment]
> No real need. 

[Musicbrainz](http://musicbrainz.org/) is the holy grail of open source music information. Those .nfo files are pretty much useless unless they link to it. Since I've decided to use it to keep everything well organized and tagged, I can't use .nfos. 

For example, here's a link to a song I have on torrenttunes:
http://torrenttunes.ml/?song=a8322e8f-cee8-49d8-808c-2578c444d656
Which has a musicbrainz link at:
http://musicbrainz.org/recording/a8322e8f-cee8-49d8-808c-2578c444d656


The musicbrainz DB is pretty massive, and although they do have docs for setting it up and replicating it yourself, I don't know if think sub-1 second song tagging is required yet. 

You'd be surprised when going through my own collection, how many songs are mis-tagged, I guesstimate about 30% of my albums were misnamed, and probably 10% of songs were. I usually scan one artist at a time, fixing the tags and making sure musicbrainz is able to identify them.

**Comment by tritnaha** [comment]
I wish you the best of luck!

I suppose you could look at magnet-links instead of creating copious amounts of torrents too, that'd be even neater.
