### ISSUE TITLE
Upload/Download Stats

### ISSUE THREAD

**Issue by Nutomic** [tchoulihan/torrenttunes-client#5]
There should be info like current upload/download, and total uploaded/downloaded.

So you see that something is happening, and that it's actually seeding.

**Comment by tchoulihan** [comment]
I originally thought about this being an overlay, but wasn't sure the best and most unobtrusive way to do it. 

After some monitoring, I decided to leave it off. Most songs are around 5-10 MB, and seeding them usually doesn't take more than 30s - 1 minute to seed them fully, even if there is only 1 seeder.  

I also don't like to query for speeds too much, since the front-end interface is request only, and every update to that page essentially has to be a repeated(I'm not using any websocket tech). 

The other alternative is to have at least the totals on a separate page.

**Comment by Nutomic** [comment]
The problem is, I have absolutely no idea if anything is evenseeded (or downloaded when I click play).

I wouldn't worry about the number of requests, eg one request per second should be totally fine (except on the public website).

And stats on a seperate page would be totally acceptable :+1:

**Comment by tchoulihan** [comment]
Good call, I'll think of the best place to put this and add it for the next release.
